-- Finance module DB changes (single script)
-- 1) organization accounts table
-- 2) account links in entrance/realization documents
-- 3) indexes for finance filters
-- 4) finance permissions seed and assignment for admin/director roles

CREATE TABLE IF NOT EXISTS organization_accounts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_name TEXT NOT NULL,
    account_number TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE entrance_documents
    ADD COLUMN IF NOT EXISTS account_id INTEGER NULL REFERENCES organization_accounts(id) ON DELETE SET NULL;

ALTER TABLE realization_documents
    ADD COLUMN IF NOT EXISTS account_id INTEGER NULL REFERENCES organization_accounts(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_entrance_documents_date
    ON entrance_documents (date);

CREATE INDEX IF NOT EXISTS idx_realization_documents_date
    ON realization_documents (date);

CREATE INDEX IF NOT EXISTS idx_entrance_documents_account_date
    ON entrance_documents (account_id, date);

CREATE INDEX IF NOT EXISTS idx_realization_documents_account_date
    ON realization_documents (account_id, date);

INSERT INTO permissions (code, name, category, description)
VALUES
    ('finance:view', 'Просмотр финансов', 'finance', 'Просмотр вкладки финансов и операций'),
    ('finance:accounts_manage', 'Управление счетами организации', 'finance', 'Создание и редактирование счетов организации')
ON CONFLICT (code) DO UPDATE
SET
    name = EXCLUDED.name,
    category = EXCLUDED.category,
    description = EXCLUDED.description;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.code IN ('finance:view', 'finance:accounts_manage')
WHERE LOWER(r.name) IN ('администратор', 'administrator', 'директор', 'director')
ON CONFLICT (role_id, permission_id) DO NOTHING;
